version: '3'
services:

  ## Config Servers
  config01:
    image: "percona/percona-server-mongodb:3.4"
    command: mongod --port 27017 --configsvr --replSet configserver --noprealloc --smallfiles --oplogSize 16 --dbpath /data/db

    volumes:
      - ./scripts:/scripts
  config02:
    image: "percona/percona-server-mongodb:3.4"
    command: mongod --port 27017 --configsvr --replSet configserver --noprealloc --smallfiles --oplogSize 16 --dbpath /data/db
    volumes:
      - ./scripts:/scripts
  config03:
    image: "percona/percona-server-mongodb:3.4"
    command: mongod --port 27017 --configsvr --replSet configserver --noprealloc --smallfiles --oplogSize 16 --dbpath /data/db
    volumes:
      - ./scripts:/scripts

  ## Shards
  shard01a:
    image: "percona/percona-server-mongodb:3.4"
    command: mongod --port 27018 --shardsvr --replSet shard01 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard01b:
    image: "percona/percona-server-mongodb:3.4"
    command: mongod --port 27018 --shardsvr --replSet shard01 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard01c:
    image: "percona/percona-server-mongodb:3.4"
    command: mongod --port 27018 --shardsvr --replSet shard01 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
 
  shard02a:
    image: "percona/percona-server-mongodb:3.4"
    command: mongod --port 27019 --shardsvr --replSet shard02 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard02b:
    image: "percona/percona-server-mongodb:3.4"
    command: mongod --port 27019 --shardsvr --replSet shard02 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard02c:
    image: "percona/percona-server-mongodb:3.4"
    command: mongod --port 27019 --shardsvr --replSet shard02 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  
  shard03a:
    image: "percona/percona-server-mongodb:3.4"
    command: mongod --port 27020 --shardsvr --replSet shard03 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard03b:
    image: "percona/percona-server-mongodb:3.4"
    command: mongod --port 27020 --shardsvr --replSet shard03 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard03c:
    image: "percona/percona-server-mongodb:3.4"
    command: mongod --port 27020 --shardsvr --replSet shard03 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts


  ## Router
  router1:
    image: "percona/percona-server-mongodb:3.4"
    command: mongos --port 27027 --configdb configserver/config01:27017,config02:27017,config03:27017
    ports:
      - "27027:27027"
    volumes:
      - ./scripts:/scripts
    depends_on:
      - config01
      - config02
      - config03
      - shard01a
      - shard01b
      - shard01c
      - shard02a
      - shard02b
      - shard02c
      - shard03a
      - shard03b
      - shard03c
  router2:
    image: "percona/percona-server-mongodb:3.4"
    command: mongos --port 27028 --configdb configserver/config01:27017,config02:27017,config03:27017
    ports:
      - "27028:27028"
    volumes:
      - ./scripts:/scripts
    depends_on:
      - config01
      - config02
      - config03
      - shard01a
      - shard01b
      - shard01c
      - shard02a
      - shard02b
      - shard02c
      - shard03a
      - shard03b
      - shard03c
